# Generated by Django 3.2.18 on 2023-02-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_remove_transaction_price_positive'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('value__gt', 0)), name='value_positive'),
        ),
    ]
