# Generated by Django 3.2.18 on 2023-02-25 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0005_transaction_value_positive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='client',
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='from_client', to='core.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='to_client', to='core.user'),
            preserve_default=False,
        ),
    ]
