# Generated by Django 3.2.18 on 2023-02-25 01:00

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_auto_20230225_0056'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('from_client', django.db.models.expressions.F('to_client')), _negated=True), name='to_client_and_from_client_can_not_be_equal'),
        ),
    ]
