# Generated by Django 3.2.18 on 2023-02-25 23:21

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_alter_account_business'),
        ('transaction', '0008_remove_transaction_to_client_and_from_client_can_not_be_equal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='from_client',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to_client',
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='from_account', to='client.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='to_account', to='client.account'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('from_account', django.db.models.expressions.F('to_account')), _negated=True), name='to_account_and_from_account_can_not_be_equal'),
        ),
    ]
