# Generated by Django 3.2.18 on 2023-02-27 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_account_balance_positive'),
        ('transaction', '0010_auto_20230227_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_account', to='client.account'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(('from_account__isnull', False), ('to_account__isnull', False), _connector='OR'), name='at_leat_one_of_to_account_or_from_account_must_be_fill'),
        ),
    ]
