# Generated by Django 3.2.18 on 2023-02-27 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_account_balance_positive'),
        ('transaction', '0009_auto_20230225_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='types',
            field=models.CharField(choices=[('DP', 'Deposits'), ('WD', 'Withdrawals'), ('EX', 'Expenses')], default='EX', max_length=2),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_account', to='client.account'),
        ),
    ]
