# Generated by Django 3.2.18 on 2023-02-27 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_delete_account'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('client', 'business')},
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_active',
        ),
    ]
