# Generated by Django 3.2.18 on 2023-02-25 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_alter_account_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='business',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.business'),
        ),
    ]
