# Generated by Django 3.2.18 on 2023-02-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_account_balance'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(check=models.Q(('balance__gt', 0)), name='balance_positive'),
        ),
    ]
